[master]
172.31.26.166 ansible_user=ubuntu ansible_ss_private_key_file_file=~/.ssh/id_rsa
[worker]
172.31.26.135 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa
[all:vars]
ansible_python_interpreter=/usr/bin/python3
