---
- name: Configuration commune (Master & Worker)
  hosts: all
  become: yes
  tasks:
    - name: Mise à jour des paquets apt
      apt:
        update_cache: yes
        upgrade: dist

    - name: Installation des dépendances
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Installation de Docker
      apt:
        name: docker.io
        state: present

    - name: Démarrage de Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Ajout de la clé GPG de Kubernetes
      apt_key:
        url: https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key
        state: present

    - name: Ajout du dépôt Kubernetes
      apt_repository:
        repo: deb https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /
        state: present

    - name: Installation de kubelet, kubeadm et kubectl
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present

    - name: Verrouillage des versions K8s
      dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop: [ 'kubelet', 'kubeadm', 'kubectl' ]

- name: Configuration du Master Node
  hosts: master
  become: yes
  tasks:
    - name: Initialisation du cluster Kubernetes
      command: kubeadm init --pod-network-cidr=10.244.0.0/16
      register: kubeadm_init
      ignore_errors: yes # Au cas où il est déjà initialisé

    - name: Création du dossier .kube pour l'utilisateur ubuntu
      file:
        path: /home/ubuntu/.kube
        state: directory
        owner: ubuntu
        group: ubuntu

    - name: Copie du fichier admin.conf pour kubectl
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu
        group: ubuntu

    - name: Installation du réseau CNI (Flannel)
      become: false
      command: kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml

    - name: Génération de la commande de join pour le worker
      command: kubeadm token create --print-join-command
      register: join_command

- name: Configuration du Worker Node
  hosts: workers
  become: yes
  tasks:
    - name: Jonction du worker au cluster
      command: "{{ hostvars['master-node']['join_command'].stdout }}"
      ignore_errors: yes
